version: "2"

services:
  db:
    image: mysql:5
    restart: unless-stopped
    networks:
      - net
    volumes:
      - ./data/db:/var/lib/mysql
    env_file: .env

  app:
    image: invoiceninja/invoiceninja
    restart: unless-stopped
    networks:
      - net
    links:
      - db:mysql
    env_file: .env
    volumes:
      - ./data/invoiceninja-storage:/var/www/app/storage:rw
      - ./data/invoiceninja-logo:/var/www/app/public/logo:rw

  web:
    image: nginx:1
    restart: unless-stopped
    networks:
      - net
    ports:
      - 8000:80
    links:
      - app
    volumes_from:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  cron:
    image: invoiceninja/invoiceninja
    #restart: unless-stopped
    networks:
      - net
    links:
      - db:mysql
    volumes_from:
      - app
    env_file: .env
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1d
      done
      EOF'

networks:
  net:
      
volumes:
  data-vol: